@Projet_Hotel_CodeBase_HostAddress = http://localhost:5292

POST {{Projet_Hotel_CodeBase_HostAddress}}/Login/login
Content-Type: application/json
{
    "logCourriel": "string",
  "logMotDePasse": "string"
    
}
###
